meta_product_name: "InFitter"
meta_title: "InFitter - Don´t look like you are trying"
meta_description: "With InFitter colormathching and creating outfits have never been easier."
meta_image: "metaimage.png" # should exist in `app/assets/images/`
